// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVhtP1w6eyUzWtdG2I0ECR-NGNrj7vvkU',
    appId: '1:724698434057:android:a0e7243cda3e34cb85c6d8',
    messagingSenderId: '724698434057',
    projectId: 'familysocial-8a04c',
    storageBucket: 'familysocial-8a04c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BMy0lXG8LHsy1aAe0ss_thv5f04tjUY',
    appId: '1:724698434057:ios:8acead97cc586e3885c6d8',
    messagingSenderId: '724698434057',
    projectId: 'familysocial-8a04c',
    storageBucket: 'familysocial-8a04c.firebasestorage.app',
    androidClientId: '724698434057-353hoiue9l19deern29inu262ucq05fc.apps.googleusercontent.com',
    iosClientId: '724698434057-scuscoo5n3f3e78bjjsm7fecfsmir3ml.apps.googleusercontent.com',
    iosBundleId: 'com.priyanshu.familySocail',
  );
}
